name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout 🛎️
        uses: actions/checkout@v2

      - name: 📕 Compile LaTeX document 📕
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true

      - name: ©️ Copy to build folder ©️
        run: bash -c 'mkdir build && cp cv.pdf build/cv.pdf'

      - name: 🚀 Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: build
          single-commit: true
