name: Build LaTeX document

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yaml'
      - 'cv.tex'
      - 'deedy-resume.cls'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout 🛎️
        uses: actions/checkout@v2

      - name: 📕 Compile LaTeX document 📕
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true

      - name: Upload files to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: cv.pdf
          asset_name: cv.pdf
          overwrite: true
          release_name: cv-latest
          body: "Latest build"
