name: Build & deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yaml'
      - 'gh-pages/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install npm dependencies
        shell: bash
        working-directory: gh-pages
        run: npm install

      - name: Download latest release
        uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          fileName: cv.pdf
          out-file-path: gh-pages

      - name: Archive the website
        shell: bash
        run: |
          tar \
            --dereference --hard-dereference \
            --directory gh-pages \
            -cvf "$RUNNER_TEMP/website.tar" \
            --exclude=.gitignore \
            .

      - name: Upload the website
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/website.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write  # Required to deploy to GitHub Pages.
      id-token: write  # Required to verify that the deployment originates from this workflow.

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy the website
        uses: actions/deploy-pages@v4